name: Integracion Continua - Sistema Escolar Hemingway

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Copiar el código del repositorio
    - name: Copiar codigo del repositorio
      uses: actions/checkout@v4

    # 2.Configurar el entorno de Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3. Simulación de instalación de dependencias del Colegio
    - name: Instalar dependencias del sistema escolar
      run: echo "Instalando modulos de asistencia y calificaciones..."

    # 4. Simulación de la compilación exitosa del Frontend Escolar
    - name: Compilar Frontend Escolar (Build)
      run: |
        echo "Validando sintaxis del codigo..."
        echo "Compilacion exitosa. El sistema Hemingway esta listo."
